apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp32
  namespace: krishna
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp32
  template:
    metadata:
      labels:
        app: myapp32
    spec:
      containers:
        - name: myapp32
          image: image2323.azurecr.io/test333-app:1.0.0
          ports: 
            - containerPort: 80
      imagePullSecrets:
            - name: krishna-santhosh01
