
apiVersion: apps/v1
kind: Deployment
metadata:
  name: santhosh-app-deployment
  namespace: myacr-kube
  labels:
    app: santhosh-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: santhosh-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: santhosh-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: environment
                    operator: In
                    values:
                      - prod
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - santhosh-app
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: santhosh-app
          image: santhosh0404/test333-app:latest
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /_status/healthz
              port: 5000
            initialDelaySeconds: 8
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: santhosh-app-deployment
              valueFrom:
                configMapKeyRef:
                  name: santhosh-app-deployment
                  key: DB_HOST
      tolerations:  
        - key: "special"
          operator: "Exists"
          effect: "NoSchedule"