apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: krishna
spec:
  selector:
    app: myapp32
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
