apiVersion: v1
kind: Service
metadata:
  name: santhosh-app-deployment
  namespace: nv1
spec:
  selector:
    app: santhosh-app-deployment
  type : LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376